{% set name = "websockets" %}
{% set version = "6.0" %}
{% set sha256 = "47bcad3e017925f8688512b4efa760807bf604a939c50c2926c40b0021247cf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/aaugustin/websockets/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - websockets

about:
  home: https://websockets.readthedocs.io/en/stable/index.html
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A library for developing WebSocket servers and clients in Python.'
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  doc_url: https://websockets.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/aaugustin/websockets

extra:
  recipe-maintainers:
    - scopatz
