{% set version = "8.0.1" %}

package:
  name: websockets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/websockets/websockets-{{ version }}.tar.gz
  sha256: d3bb8f0b1310b41b727c890353e058b335d1eec18995a82a108ca4784d0e3f94

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<34]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - websockets

about:
  home: https://websockets.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A library for developing WebSocket servers and clients in Python.'
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  doc_url: https://websockets.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/aaugustin/websockets

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
