{% set name = "websockets" %}
{% set version = "13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a3b3366087c1bc0a2795111edcadddb8b3b59509d5db5d7ea3fdd69f954a8878
  - url: https://github.com/python-websockets/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 39345b087381694ca06c5b2b922aa8c2a54dc8f08fcaee358eafaa2222c4dd22
    folder: gh

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

{% set ignore_tests = "" %}
# OSError: [Errno 99] error while attempting to bind on address ('::1', 0, 0, 0): cannot assign requested address
{% set ignore_tests = "--ignore=gh/tests/legacy/test_auth.py" %}  # [linux] 
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/legacy/test_client_server.py" %}  # [linux]
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/asyncio/test_client.py" %}  # [linux] 
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/asyncio/test_server.py" %}  # [linux]
# websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/sync/test_connection.py" %}  # [osx]

test:
  source_files:
    - gh/tests
  imports:
    - websockets
    - websockets.asyncio
    - websockets.client
    - websockets.datastructures
    - websockets.exceptions
    - websockets.frames
    - websockets.headers
    - websockets.http11
    - websockets.imports
    - websockets.legacy
    - websockets.protocol
    - websockets.server
    - websockets.streams
    - websockets.sync
    - websockets.typing
    - websockets.uri
    - websockets.utils
    - websockets.version
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Tests on Windows randomly hang or fail to start without any issue.
    # These tests time out intermittently
    - pytest {{ ignore_tests }} -v gh/tests -k "not (test_close_server_keeps_handlers_running or test_close_waits_for_close_frame)"  # [unix]

  requires:
    - pip
    - pytest
    - werkzeug

about:
  home: https://websockets.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: websockets is a library for building WebSocket servers and clients in 
    Python with a focus on correctness, simplicity, robustness, and performance.
  description: |
    websockets is a library for building WebSocket servers and clients in Python with a focus on correctness, simplicity, robustness, and performance.
    It supports several network I/O and control flow paradigms.
    The default implementation builds upon asyncio, Python’s built-in asynchronous I/O library. 
    It provides an elegant coroutine-based API. It’s ideal for servers that handle many client connections.
    The threading implementation is a good alternative for clients, especially if you aren’t familiar with asyncio. 
    It may also be used for servers that handle few client connections.
    The Sans-I/O implementation is designed for integrating in third-party libraries, 
    typically application servers, in addition being used internally by websockets.
  doc_url: https://websockets.readthedocs.io
  dev_url: https://github.com/python-websockets/websockets

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf