{% set name = "websockets" %}
{% set version = "10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eef610b23933c54d5d921c92578ae5f89813438fded840c2e9809d378dc765d3

build:
  number: 2
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - websockets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://websockets.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  doc_url: https://websockets.readthedocs.io/
  dev_url: https://github.com/aaugustin/websockets

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
