travis:
  secure:
    BINSTAR_TOKEN: Bxhv38uGYDCyXZcKA9FL4FcFw9hj3bvtGxFXtIThSrSFu7cXttWmk8p20kEyJXBautOPWUiJGf/mjgiaawboxn7G4yS1fhgYPBbygq+PwjQLyC8OzTalHsP0HRpGn+h2tW5DH953taeoa+AAMBqGmRmuTqcpxsNPh3Bihc71DgJrct4IzNsgxBBkxNZ0KaJ6AHwMTOxfd/Al8+krPzykXdTP8m9iL6yL0084EFhEunMZop9mE3iHnEFG4lxp/JchU28y4zZKy+cIcA6ot36IvYAao1IuhJfcLzEhsMKYMhDayYxFvHfbJsZtoD63o074xTjBaKmUbpo9Qh0BY86zvcy+QEz1XsrFn7fR1LZm1GS0o2RG2TysWZsEdNuEmhlv6PA1z4XAO8V/1QQQkq/lXrOBbsFtpKsJAStWxL4oClqoc00dpgEI8328LwGcyAvH6HZCJDp8Zb7jtpqDsiezw2tTuUGEw3FqKTtXAkfXt0pLY7PG9y8wCTxU3ukDaYbiZQXIk7go2c10MbZY54nFri2H3x3Z8K51UkPRFYC2NZFPgfoaVraMhwx31lCQXYKPS5vXjdPX1dmHfoPSNS5dUV5CMM2BwafD4BTgMt594dV/ccrQZqQOoUnYx1gPuh0rddelFyGi55wNEe0F/f3RVK1Y54K9XPnf19k2hdbLOnA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
