travis:
  secure:
    BINSTAR_TOKEN: TQbCLAmMqurffYPqpkgPgn8dG04hIYTw2QVyeDm+TU0c6iMhezeugCIZzBSpvpi/NZsFCRPCPOsQircvRobDT1SzfWHMf3xKpXdA7hcp38+YY4GA3ES0CiQBN+I7/00TLVPzYVmw0IiwYmi8UNyn3tXC31JOE+qw7ujGVQKNgb8TsPuLjgSeCaYLRnudtJiesa3XtntDtiG0eHumiHn8wcPo44EYGqd48PjYgPvvJrDpNDwnti+AwQwtDvyUKjWZlVZ/4bnAjFVmnNYb9o6uwkqeOywYACyBVgGAH6q87Oy+U63+WclDEqB7xGx3v4MiNSlDAATitLMH1sMJZfoRaCU0wxjkHPswQpRLxdHXUV28tmJvjVVYqXYHRu+1xtuiAMFGTI/yeuJk6BA4MuGeh/Jq3cFjjVvwdvm3q0o3c2iildjdcNQjS0uyPUOVMzQyGeRh61SvYu7i911b1/A4TkyzC/EqLSRs7yOGTJ3yRCiRKaM8vqw6pcoDcQeWnNQx/lZaYMfuhGzLxm7nJNfgEcWugOlN6jk+IeSDWVamJQO4xWoRZ8zi1fCgygXfS7F98Lf0OCQoWFjxgeBMAOxFG7IRiRZeJIbJ0qS5q7TM/btmQpqJbwmarWi3WZfJ7ujIt4vxHDHDQsbybVeuyiVcJ3OUkxRffzIdeL/bZG0luwE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
